final Map<String, Map<String, dynamic>> seedTeams = {
  'rma': {
    'name': {'en': 'Real Madrid', 'zh': '皇家马德里'},
    'alias': {'en': 'Real Madrid', 'zh': '皇马'},
    'short': 'RMA',
    'primary': '#FFFFFF',
    'accent': '#FEBE10',
    'sub': '#00529F',
    'city': {'en': 'Madrid, Spain', 'zh': '马德里, 西班牙'},
    'leagueId': 'lal',
    'rank': {'en': '1st in La Liga', 'zh': '西甲第 1'},
    'flag': '🇪🇸',
  },
  'bar': {
    'name': {'en': 'Barcelona', 'zh': '巴塞罗那'},
    'alias': {'en': 'Barcelona', 'zh': '巴萨'},
    'short': 'BAR',
    'primary': '#A50044',
    'accent': '#004D98',
    'sub': '#EDBB00',
    'city': {'en': 'Barcelona, Spain', 'zh': '巴塞罗那, 西班牙'},
    'leagueId': 'lal',
    'rank': {'en': '2nd in La Liga', 'zh': '西甲第 2'},
    'flag': '🇪🇸',
  },
  'mci': {
    'name': {'en': 'Manchester City', 'zh': '曼彻斯特城'},
    'alias': {'en': 'Man City', 'zh': '曼城'},
    'short': 'CITY',
    'primary': '#6CABDD',
    'accent': '#1C2C5B',
    'sub': '#FFC659',
    'city': {'en': 'Manchester, UK', 'zh': '曼彻斯特, 英格兰'},
    'leagueId': 'epl',
    'rank': {'en': '2nd in Premier League', 'zh': '英超第 2'},
    'flag': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  },
  'psg': {
    'name': {'en': 'Paris SG', 'zh': '巴黎圣日耳曼'},
    'alias': {'en': 'PSG', 'zh': '巴黎'},
    'short': 'PSG',
    'primary': '#004170',
    'accent': '#DA291C',
    'sub': '#FFFFFF',
    'city': {'en': 'Paris, France', 'zh': '巴黎, 法国'},
    'leagueId': 'lal',
    'rank': {'en': '1st in Ligue 1', 'zh': '法甲第 1'},
    'flag': '🇫🇷',
  },
  'bay': {
    'name': {'en': 'Bayern Munich', 'zh': '拜仁慕尼黑'},
    'alias': {'en': 'Bayern', 'zh': '拜仁'},
    'short': 'FCB',
    'primary': '#DC052D',
    'accent': '#0066B2',
    'sub': '#FFFFFF',
    'city': {'en': 'Munich, Germany', 'zh': '慕尼黑, 德国'},
    'leagueId': 'bun',
    'rank': {'en': '1st in Bundesliga', 'zh': '德甲第 1'},
    'flag': '🇩🇪',
  },
  'ars': {
    'name': {'en': 'Arsenal', 'zh': '阿森纳'},
    'alias': {'en': 'Arsenal', 'zh': '枪手'},
    'short': 'ARS',
    'primary': '#EF0107',
    'accent': '#063672',
    'sub': '#9C824A',
    'city': {'en': 'London, UK', 'zh': '伦敦, 英格兰'},
    'leagueId': 'epl',
    'rank': {'en': '1st in Premier League', 'zh': '英超第 1'},
    'flag': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  },
  'liv': {
    'name': {'en': 'Liverpool', 'zh': '利物浦'},
    'alias': {'en': 'Liverpool', 'zh': '红军'},
    'short': 'LIV',
    'primary': '#C8102E',
    'accent': '#F6EB61',
    'sub': '#00B2A9',
    'city': {'en': 'Liverpool, UK', 'zh': '利物浦, 英格兰'},
    'leagueId': 'epl',
    'rank': {'en': '3rd in Premier League', 'zh': '英超第 3'},
    'flag': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  },
  'int': {
    'name': {'en': 'Inter Milan', 'zh': '国际米兰'},
    'alias': {'en': 'Inter', 'zh': '国米'},
    'short': 'INT',
    'primary': '#0033A0',
    'accent': '#000000',
    'sub': '#FFFFFF',
    'city': {'en': 'Milan, Italy', 'zh': '米兰, 意大利'},
    'leagueId': 'ser',
    'rank': {'en': '1st in Serie A', 'zh': '意甲第 1'},
    'flag': '🇮🇹',
  },
  'bvb': {
    'name': {'en': 'Dortmund', 'zh': '多特蒙德'},
    'alias': {'en': 'Dortmund', 'zh': '多特'},
    'short': 'BVB',
    'primary': '#FDE100',
    'accent': '#000000',
    'sub': '#FFFFFF',
    'city': {'en': 'Dortmund, Germany', 'zh': '多特蒙德, 德国'},
    'leagueId': 'bun',
    'rank': {'en': '4th in Bundesliga', 'zh': '德甲第 4'},
    'flag': '🇩🇪',
  },
  'juv': {
    'name': {'en': 'Juventus', 'zh': '尤文图斯'},
    'alias': {'en': 'Juventus', 'zh': '尤文'},
    'short': 'JUV',
    'primary': '#000000',
    'accent': '#FFFFFF',
    'sub': '#9C824A',
    'city': {'en': 'Turin, Italy', 'zh': '都灵, 意大利'},
    'leagueId': 'ser',
    'rank': {'en': '2nd in Serie A', 'zh': '意甲第 2'},
    'flag': '🇮🇹',
  },
  'che': {
    'name': {'en': 'Chelsea', 'zh': '切尔西'},
    'alias': {'en': 'Chelsea', 'zh': '蓝军'},
    'short': 'CHE',
    'primary': '#034694',
    'accent': '#FFFFFF',
    'sub': '#DBA111',
    'city': {'en': 'London, UK', 'zh': '伦敦, 英格兰'},
    'leagueId': 'epl',
    'rank': {'en': '5th in Premier League', 'zh': '英超第 5'},
    'flag': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  },
  'atm': {
    'name': {'en': 'Atlético Madrid', 'zh': '马德里竞技'},
    'alias': {'en': 'Atlético', 'zh': '马竞'},
    'short': 'ATM',
    'primary': '#CB3524',
    'accent': '#272E61',
    'sub': '#FFFFFF',
    'city': {'en': 'Madrid, Spain', 'zh': '马德里, 西班牙'},
    'leagueId': 'lal',
    'rank': {'en': '3rd in La Liga', 'zh': '西甲第 3'},
    'flag': '🇪🇸',
  },
};

final Map<String, Map<String, dynamic>> seedComps = {
  'ucl': {
    'name': {'en': 'UEFA Champions League', 'zh': '欧洲冠军联赛'},
    'short': {'en': 'UCL', 'zh': '欧冠'},
    'accent': '#1E3A8A',
    'glyph': '★',
  },
  'epl': {
    'name': {'en': 'Premier League', 'zh': '英格兰超级联赛'},
    'short': {'en': 'EPL', 'zh': '英超'},
    'accent': '#37003C',
    'glyph': '♛',
  },
  'lal': {
    'name': {'en': 'La Liga', 'zh': '西班牙甲级联赛'},
    'short': {'en': 'La Liga', 'zh': '西甲'},
    'accent': '#EE8B00',
    'glyph': '◆',
  },
  'bun': {
    'name': {'en': 'Bundesliga', 'zh': '德国甲级联赛'},
    'short': {'en': 'BL', 'zh': '德甲'},
    'accent': '#D20515',
    'glyph': '◉',
  },
  'ser': {
    'name': {'en': 'Serie A', 'zh': '意大利甲级联赛'},
    'short': {'en': 'SerieA', 'zh': '意甲'},
    'accent': '#008FD7',
    'glyph': '⬢',
  },
  'wcf': {
    'name': {'en': 'World Cup', 'zh': '国际足联世界杯'},
    'short': {'en': 'WC', 'zh': '世界杯'},
    'accent': '#D4AF37',
    'glyph': '🏆',
  },
  'eur': {
    'name': {'en': 'EURO', 'zh': '欧洲杯'},
    'short': {'en': 'EURO', 'zh': '欧洲杯'},
    'accent': '#0F4C81',
    'glyph': '✦',
  },
};

List<Map<String, dynamic>> buildSeedMatches() {
  final now = DateTime.now().millisecondsSinceEpoch;
  return [
    {
      'id': 'ucl-final',
      'comp': 'ucl',
      'stage': {'en': 'Final', 'zh': '决赛'},
      'home': 'rma',
      'away': 'bar',
      'kickoff': now + (2 * 24 + 14) * 3600000 + 22 * 60000,
      'venue': {'en': 'Wembley Stadium', 'zh': '温布利球场'},
      'city': {'en': 'London, England', 'zh': '伦敦, 英格兰'},
      'featured': true,
      'players': [
        {'team': 'rma', 'name': {'en': 'Vinicius Jr.', 'zh': '维尼修斯'}, 'pos': {'en': 'LW', 'zh': '左边锋'}, 'num': 7, 'stat': {'en': '23 goals · 12 assists', 'zh': '23 球 · 12 助攻'}, 'photo': 'vinicius'},
        {'team': 'rma', 'name': {'en': 'Jude Bellingham', 'zh': '贝林厄姆'}, 'pos': {'en': 'AM', 'zh': '前腰'}, 'num': 5, 'stat': {'en': '18 goals · 14 assists', 'zh': '18 球 · 14 助攻'}, 'photo': 'bellingham'},
        {'team': 'rma', 'name': {'en': 'Kylian Mbappé', 'zh': '姆巴佩'}, 'pos': {'en': 'ST', 'zh': '中锋'}, 'num': 9, 'stat': {'en': '31 goals · 8 assists', 'zh': '31 球 · 8 助攻'}, 'photo': 'mbappe'},
        {'team': 'bar', 'name': {'en': 'Lamine Yamal', 'zh': '亚马尔'}, 'pos': {'en': 'RW', 'zh': '右边锋'}, 'num': 19, 'stat': {'en': '17 goals · 21 assists', 'zh': '17 球 · 21 助攻'}, 'photo': 'yamal'},
        {'team': 'bar', 'name': {'en': 'Pedri', 'zh': '佩德里'}, 'pos': {'en': 'CM', 'zh': '中场'}, 'num': 8, 'stat': {'en': '7 goals · 16 assists', 'zh': '7 球 · 16 助攻'}, 'photo': 'pedri'},
        {'team': 'bar', 'name': {'en': 'R. Lewandowski', 'zh': '莱万多夫斯基'}, 'pos': {'en': 'ST', 'zh': '中锋'}, 'num': 9, 'stat': {'en': '28 goals · 6 assists', 'zh': '28 球 · 6 助攻'}, 'photo': 'lewandowski'},
      ],
    },
    {
      'id': 'm2',
      'comp': 'ucl',
      'stage': {'en': 'Group · MD6', 'zh': '小组赛 · 第 6 轮'},
      'home': 'mci',
      'away': 'psg',
      'kickoff': now + 2 * 3600000 + 22 * 60000,
      'venue': {'en': 'Etihad Stadium', 'zh': '阿提哈德球场'},
      'city': {'en': 'Manchester, England', 'zh': '曼彻斯特, 英格兰'},
    },
    {
      'id': 'm3',
      'comp': 'epl',
      'stage': {'en': 'Matchday 38', 'zh': '第 38 轮'},
      'home': 'ars',
      'away': 'liv',
      'kickoff': now + 26 * 3600000,
      'venue': {'en': 'Emirates Stadium', 'zh': '酋长球场'},
      'city': {'en': 'London, England', 'zh': '伦敦, 英格兰'},
    },
    {
      'id': 'm4',
      'comp': 'bun',
      'stage': {'en': 'Matchday 34', 'zh': '第 34 轮'},
      'home': 'bay',
      'away': 'bvb',
      'kickoff': now + (24 + 18) * 3600000 + 30 * 60000,
      'venue': {'en': 'Allianz Arena', 'zh': '安联球场'},
      'city': {'en': 'Munich, Germany', 'zh': '慕尼黑, 德国'},
    },
    {
      'id': 'm5',
      'comp': 'ser',
      'stage': {'en': 'Matchday 38', 'zh': '第 38 轮'},
      'home': 'int',
      'away': 'juv',
      'kickoff': now + (3 * 24 + 2) * 3600000,
      'venue': {'en': 'San Siro', 'zh': '圣西罗球场'},
      'city': {'en': 'Milan, Italy', 'zh': '米兰, 意大利'},
    },
    {
      'id': 'm6',
      'comp': 'lal',
      'stage': {'en': 'Matchday 38', 'zh': '第 38 轮'},
      'home': 'atm',
      'away': 'rma',
      'kickoff': now + (4 * 24 + 5) * 3600000,
      'venue': {'en': 'Metropolitano', 'zh': '万达大都会球场'},
      'city': {'en': 'Madrid, Spain', 'zh': '马德里, 西班牙'},
    },
    {
      'id': 'm7',
      'comp': 'epl',
      'stage': {'en': 'Matchday 38', 'zh': '第 38 轮'},
      'home': 'mci',
      'away': 'che',
      'kickoff': now + (5 * 24 + 1) * 3600000,
      'venue': {'en': 'Etihad Stadium', 'zh': '阿提哈德球场'},
      'city': {'en': 'Manchester, England', 'zh': '曼彻斯特, 英格兰'},
    },
    {
      'id': 'm8',
      'comp': 'ucl',
      'stage': {'en': 'Group · MD6', 'zh': '小组赛 · 第 6 轮'},
      'home': 'juv',
      'away': 'ars',
      'kickoff': now + (7 * 24 + 3) * 3600000,
      'venue': {'en': 'Allianz Stadium', 'zh': '尤文图斯竞技场'},
      'city': {'en': 'Turin, Italy', 'zh': '都灵, 意大利'},
    },
  ];
}
